# site settings
title: Zulia
subtitle:
email: inquiry@ascend-tech.us
description: Replicated Distributed Lucene with deep object searching.
baseurl:  # the subpath of your site, e.g. /blog
url: https://zulia.io # the base hostname & protocol for your site
author:
street_address: 
city: 
state: Maryland
zip_code: 
country: USA
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
socials:
  GitHub: https://github.com/zuliaio/zuliasearch
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/company/ascendant-software-technology-llc/
  Twitter: https://twitter.com/zulia
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed
