# site settings
title: Zulia
subtitle:
email: inquiry@ascend-tech.us
description: Replicated Distributed Lucene with deep object searching.
baseurl:  # the subpath of your site, e.g. /blog
url: http://zulia.io # the base hostname & protocol for your site
author:
street_address: 
city: 
state: Maryland
zip_code: 
country: USA
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url: https://github.com/zuliaio/zuliasearch
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zulia

# build settings
markdown: kramdown

sass:
  style: compressed
